const assert=require('node:assert/strict');
const http=require('node:http');const fs=require('node:fs');const path=require('node:path');
const puppeteer=require('puppeteer');
const fixture=require('./build-accent-fixture.cjs')();const root=fixture.root;const productionRoot=path.resolve('out');
const server=http.createServer((req,res)=>{
  const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);
  let file=path.resolve(root,'.'+(pathname.endsWith('/')?`${pathname}index.html`:pathname));
  if(!file.startsWith(root+path.sep)){res.writeHead(404);res.end();return;}
  if(!fs.existsSync(file))file=path.resolve(productionRoot,'.'+pathname);
  if(!file.startsWith(productionRoot+path.sep)&&!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);res.end();return;}
  const type={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.webp':'image/webp'}[path.extname(file)]||'application/octet-stream';
  res.setHeader('Content-Type',type);fs.createReadStream(file).pipe(res);
});
(async()=>{
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  const origin=`http://127.0.0.1:${server.address().port}`;
  const browser=await puppeteer.launch({headless:true,executablePath:process.env.CHROME_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage']});
  const page=await browser.newPage();const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  fs.mkdirSync('test/ui-previews',{recursive:true});
  try{
    await page.setViewport({width:393,height:851,deviceScaleFactor:1});
    await page.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'no-preference'}]);
    await page.evaluateOnNewDocument(()=>{
      const Original=Date;const now=Original.parse('2026-10-06T12:18:30Z');
      window.Date=class extends Original {constructor(...args){super(...(args.length?args:[now]));}static now(){return now;}};
    });
    await page.setRequestInterception(true);
    let showFixtureBus=false, showMarcel=false;
    const marcelRoad=require('./fixtures/marcel-jaslo-rzeszow-1181798.json');
    const {decodePolyline}=require('./load-ts.cjs')('lib/bus-road-geometry.ts');
    let marcelSecondary=0;
    let fixtureBus=structuredClone(require('./fixtures/pks-vehicle.json'));
    fixtureBus.trip_id=987654321; // A live ID absent from the packaged GTFS index.
    fixtureBus.position.position_date='2026-10-06 14:18:30';
    fixtureBus.journey.vehicle_journey_date='2026-10-06';fixtureBus.journey.departure_time='14:25:00';
    fixtureBus.next_stop_points=fixtureBus.next_stop_points.map((stop,index)=>({...stop,planned_departure_time:`2026-10-06 14:${String(25+index*2).padStart(2,'0')}:00`,real_departure_time:`2026-10-06 14:${String(25+index*2).padStart(2,'0')}:00`}));
    page.on('request',async request=>{
      const url=request.url();
      const json=data=>request.respond({status:200,contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:JSON.stringify(data)});
      if(url.includes('stop-point-timetable'))return json({success:true,items:[{line_name:'108',description:'Rzeszów',journeys:[{journey_id:1,time:'14:21',stop_point_code:'69',legends:['D']}]}]});
      if(url.includes('/pks/get_vehicles.php'))return json(showFixtureBus?[fixtureBus]:[]);
      if(url.endsWith('/api/pks/vehicles'))return json({items:[]});
      if(url.includes('/api/pks/einfo/stop-point'))return json({items:[]});
      if(showMarcel && url.includes('/trasy/lokalizacjaBusow'))return json([{idKu:1181798,idPo:42,szGps:49.95,dlGps:21.88,nazTr:'Jasło-Rzeszów',timestamp:'2026-10-06T12:18:30Z'}]);
      if(showMarcel && url.includes('/trasy/kurs/1181798'))return json(marcelRoad.course);
      if(showMarcel && (url.includes('valhalla')||url.includes('router.project-osrm.org'))) {
        const points=url.includes('valhalla')?JSON.parse(new URL(url).searchParams.get('json')).locations.map(p=>[p.lat,p.lon]):new URL(url).pathname.split('/driving/')[1].split(';').map(p=>p.split(',').map(Number).reverse());
        const chunk=marcelRoad.chunks.find(c=>JSON.stringify(c.stops)===JSON.stringify(points));
        if(!chunk)return json({error:'Unexpected route pattern'});
        if(url.includes('valhalla'))return json({trip:{legs:chunk.primary}});
        marcelSecondary++;return json({code:'Ok',routes:[{geometry:{coordinates:decodePolyline(chunk.secondary).map(([a,b])=>[b,a])}}]});
      }
      if(url.includes('mpkrzeszow.pl')||url.includes('api-site.marcel-bus.pl'))return json([]);
      if(url.startsWith(origin))return request.continue();
      return request.abort();
    });
    const button=async label=>page.evaluate(text=>[...document.querySelectorAll('button')].find(el=>el.textContent.trim()===text)?.click(),label);
    const visible=async selector=>{
      await page.waitForFunction(css=>[...document.querySelectorAll(css)].some(el=>{const r=el.getBoundingClientRect();return r.width>0&&r.height>0&&r.right>0&&r.left<innerWidth&&r.bottom>0&&r.top<innerHeight;}),{},selector);
      const handle=await page.evaluateHandle(css=>[...document.querySelectorAll(css)].find(el=>{const r=el.getBoundingClientRect();return r.width>0&&r.height>0&&r.right>0&&r.left<innerWidth&&r.bottom>0&&r.top<innerHeight;}),selector);
      return handle.asElement();
    };
    const style=async(selector,property)=>(await visible(selector)).evaluate((el,key)=>getComputedStyle(el)[key],property);
    const openStops=async()=>{
      console.log('Opening stops');
      await page.waitForFunction(()=>document.documentElement.style.getPropertyValue('--pks-accent').trim()!=='');
      await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(el=>el.textContent.trim()==='Przystanki'));
      await button('Przystanki');await page.waitForSelector('input[placeholder*="Babica"]');
      await page.type('input[placeholder*="Babica"]','Baryczka');
      await page.waitForFunction(()=>[...document.querySelectorAll('h3')].some(el=>el.textContent==='Baryczka 69'));
      await new Promise(resolve=>setTimeout(resolve,650));
    };
    const accent=async name=>{
      console.log('Selecting accent:',name);
      await button('Opcje');await page.waitForSelector('[role="dialog"]');
      await page.click(`[aria-label="Kolor akcentu: ${name}"]`);
      await page.mouse.click(4,4);await page.waitForSelector('[role="dialog"]',{hidden:true});
    };
    const overflow=async()=>assert.equal(await page.evaluate(()=>[...document.querySelectorAll('.transit-view')].some(el=>el.scrollWidth>el.clientWidth+1)),false);
    const screenshot=async name=>{await new Promise(resolve=>setTimeout(resolve,650));return page.screenshot({path:`test/ui-previews/${name}.png`});};
    await page.goto(origin,{waitUntil:'domcontentloaded'});
    console.log('App loaded');
    await page.waitForFunction(()=>document.documentElement.style.getPropertyValue('--pks-accent').trim()!=='');
    await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(el=>el.textContent.trim()==='Opcje'));
    await page.waitForSelector('[data-ui-theme="dark-oled"]');
    assert.equal(await page.evaluate(()=>localStorage.getItem('mks_app_theme')),null,'AMOLED is the default without overwriting a saved preference');
    await page.click('[aria-label="Przewoźnicy"]');await page.waitForSelector('[data-carrier-grid]');
    assert.equal(await page.$eval('[data-carrier-sheet]',el=>el.dataset.glass),'on');
    assert.notEqual(await page.$eval('[data-carrier-sheet]',el=>getComputedStyle(el).backdropFilter),'none');
    assert.equal(await page.$$eval('[data-carrier-grid] img',els=>els.length),0,'bus selection uses no raster artwork');
    assert.equal(await page.$$eval('[data-carrier-bus-svg]',els=>els.length),3);
    const carrierGeometry=await page.$eval('[data-carrier-grid] button[aria-label="PKS Rzeszów"] svg[data-bus-glyph]',el=>[...el.querySelectorAll('rect,circle')].map(node=>[node.tagName,...['x','y','width','height','rx','cx','cy','r'].map(key=>node.getAttribute(key))]));
    assert.equal(carrierGeometry.length,6,'the carrier comparison selects the bus rather than the checkmark');
    const pksSelected=await page.$eval('[data-carrier-grid] button[aria-label="PKS Rzeszów"]',el=>el.getAttribute('aria-pressed'));
    await page.click('[data-carrier-grid] button[aria-label="PKS Rzeszów"]');
    assert.notEqual(await page.$eval('[data-carrier-grid] button[aria-label="PKS Rzeszów"]',el=>el.getAttribute('aria-pressed')),pksSelected);
    await page.click('[data-carrier-grid] button[aria-label="PKS Rzeszów"]');
    assert.ok(await page.$eval('[data-carrier-grid]',el=>el.scrollWidth<=el.clientWidth+1));
    await screenshot('carriers-amoled');await page.click('[aria-label="Zamknij panel przewoźników"]');
    // Check saved theme in a fresh document, preserving the browser context's
    // storage. Page.reload sporadically times out at this animated-view boundary.
    await page.evaluate(()=>localStorage.setItem('mks_app_theme','dark'));
    await page.goto('about:blank');await page.goto(origin,{waitUntil:'domcontentloaded'});
    await page.waitForSelector('[data-ui-theme="dark"]');
    await accent('Fioletowy');
    await button('Przystanki');
    await page.waitForFunction(()=>document.querySelectorAll('[data-stop-card-id]').length>=3);
    await page.evaluate(()=>{const button=[...document.querySelectorAll('button')].find(el=>el.textContent.trim().startsWith('Pokaż wszystkie ('));button.scrollIntoView();});
    const previewScroll=await page.$eval('[data-stop-list-scroll]',el=>el.scrollTop);
    await page.evaluate(()=>[...document.querySelectorAll('button')].find(el=>el.textContent.trim().startsWith('Pokaż wszystkie (')).click());
    await page.waitForSelector('[data-stop-list-mode="full"]');
    assert.ok(await page.$eval('[data-stop-list-mode="full"]',el=>Number(getComputedStyle(el).opacity))<1,'full list enters with a fade instead of teleporting');
    await new Promise(resolve=>setTimeout(resolve,650));
    assert.equal(await page.$$eval('[data-stop-list-scroll]',els=>els.length),1,'full view replaces the preview scroll container');
    assert.equal(await page.$$eval('input[placeholder*="Babica"]',els=>els.length),1,'full view has no preview header underneath');
    const assertCards=async()=>assert.equal(await page.$$eval('[data-stop-card-id]',cards=>cards.every((card,index)=>{
      const bounds=card.getBoundingClientRect();const next=cards[index+1]?.getBoundingClientRect();
      return bounds.height>=70&&(!next||bounds.bottom<=next.top+1);
    })),true,'full stop cards retain their height and never overlap');
    await page.waitForSelector('[data-virtual-stop-cards]');await assertCards();assert.equal(await page.$eval('[data-virtual-stop-cards]',el=>Number(el.dataset.totalStops)),40);assert.ok(await page.$$eval('[data-stop-card-id]',els=>els.length)<25,'full list renders only nearby cards');
    await screenshot('stops-full-glass');
    await page.evaluate(()=>[...document.querySelectorAll('button')].find(el=>el.textContent.trim().startsWith('Pokaż więcej (')).click());
    await page.waitForFunction(()=>document.querySelector('[data-virtual-stop-cards]').dataset.totalStops==='80');await assertCards();assert.ok(await page.$$eval('[data-stop-card-id]',els=>els.length)<25,'loading more stops does not inflate DOM');
    await page.$eval('[data-stop-list-scroll]',el=>{el.scrollTop=500;});
    assert.ok(await page.$eval('[data-stop-list-scroll]',el=>el.scrollTop)>=499,'full list scrolls independently');
    await page.click('[aria-label="Zamknij pełną listę przystanków"]');
    await page.waitForSelector('[data-stop-list-mode="preview"]');
    assert.equal(await page.$$eval('[data-stop-card-id]',els=>els.length),30);
    assert.ok(Math.abs(await page.$eval('[data-stop-list-scroll]',el=>el.scrollTop)-previewScroll)<2,'closing restores the previous scroll position');
    // Browser and Android use the same dispatcher. Each press must consume one view.
    await page.evaluate(()=>[...document.querySelectorAll('button')].find(el=>el.textContent.trim().startsWith('Pokaż wszystkie (')).click());
    await page.waitForSelector('[data-full-stop-list]');
    await new Promise(resolve=>setTimeout(resolve,650));
    await page.click('[data-full-stop-list] [data-stop-card-id]');
    await page.waitForSelector('[aria-label="Wróć do listy przystanków"]');
    await page.evaluate(()=>history.back());
    await page.waitForSelector('[data-full-stop-list]');
    assert.equal(await page.$eval('[data-full-stop-list]',el=>el.closest('[aria-hidden]').getAttribute('aria-hidden')),'false','Back from detail stays on stops and restores the full list');
    await page.waitForFunction(()=>history.state?.pksBackGuard===true);
    await page.evaluate(()=>history.back());
    await page.waitForSelector('[data-stop-list-mode="preview"]');
    assert.equal(await page.$eval('[data-stop-list-mode="preview"]',el=>el.closest('[aria-hidden]').getAttribute('aria-hidden')),'false','second Back closes only the full list');
    await new Promise(resolve=>setTimeout(resolve,650));
    await page.$eval('[data-stop-list-scroll]',el=>{el.scrollTop=0;});
    const favorite=await page.evaluate(()=>{const card=document.querySelectorAll('[data-stop-card-id]')[2];return {id:card.dataset.stopCardId,top:card.getBoundingClientRect().top};});
    await page.evaluate(id=>document.querySelector(`[data-stop-card-id="${id}"] [aria-label="Dodaj do ulubionych"]`).click(),favorite.id);
    await page.waitForFunction(id=>{const card=document.querySelector(`[data-stop-card-id="${id}"]`);return card.style.transform&&card.style.transform!=='none';},{},favorite.id);
    await new Promise(resolve=>setTimeout(resolve,650));
    assert.ok(await page.evaluate(id=>document.querySelector(`[data-stop-card-id="${id}"]`).getBoundingClientRect().top,favorite.id)<favorite.top-20,'favourite card moves smoothly to the top');
    await openStops();
    await page.waitForFunction(()=>getComputedStyle(document.documentElement).getPropertyValue('--pks-accent').trim()==='#8b5cf6');
    const brandBefore=await style('.transit-stop-card .text-teal-400','color');
    const before=await style('.transit-stop-card .ui-accent-soft','backgroundColor');
    await (await visible('.transit-stop-card [aria-label="Dodaj do ulubionych"]')).click();await visible('.transit-stop-card .ui-accent-fill');
    await overflow();await screenshot('stops-dark-purple');
    await page.evaluate(()=>[...document.querySelectorAll('h3')].find(el=>el.textContent==='Baryczka 69'&&el.getClientRects().length).click());
    await page.waitForSelector('button[data-selected="true"]');
    await page.waitForFunction(()=>document.querySelector('.transit-view').innerText.includes('Rzeszów'));
    assert.equal(await style('.transit-view button.ui-accent-solid','backgroundColor'),'rgb(139, 92, 246)');
    await overflow();await screenshot('departures-dark-purple');
    assert.ok(await page.$eval('.transit-view',el=>parseFloat(getComputedStyle(el).paddingBottom))<=90,'departure detail has one compact bottom inset');
    assert.equal(await page.$eval('[data-stop-lines]',el=>parseFloat(getComputedStyle(el).paddingBottom)),0,'line badges do not add a second spacer');
    await accent('Niebieski');
    assert.equal(await style('.transit-view button.ui-accent-solid','backgroundColor'),'rgb(59, 130, 246)');
    await (await visible('[aria-label="Pokaż przystanek na mapie"]')).click();
    await page.waitForSelector('[data-map-stop-sheet]');
    await page.evaluate(()=>history.back());
    await page.waitForFunction(()=>{const button=document.querySelector('[aria-label="Wróć do listy przystanków"]');return button&&button.closest('[aria-hidden]').getAttribute('aria-hidden')==='false';});
    await page.waitForSelector('[data-map-stop-sheet]',{hidden:true});
    assert.equal(await page.$('[data-map-stop-sheet]'),null,'Back from a map preview returns to its stop detail');

    await (await visible('[aria-label="Wróć do listy przystanków"]')).click();
    const after=await style('.transit-stop-card .ui-accent-soft','backgroundColor');
    assert.notEqual(before,after);
    assert.equal(await style('.transit-stop-card .text-teal-400','color'),brandBefore);
    await page.evaluate(()=>localStorage.setItem('mks_app_theme','light'));
    await page.reload({waitUntil:'domcontentloaded'});await openStops();
    await page.waitForFunction(()=>getComputedStyle(document.documentElement).getPropertyValue('--pks-accent').trim()==='#3b82f6');
    assert.equal(await page.$eval('.transit-view',el=>el.dataset.uiMode),'light');
    await overflow();await screenshot('stops-light-blue');
    const showStopOnMap=async()=>{
      await page.evaluate(()=>[...document.querySelectorAll('h3')].find(el=>el.textContent==='Baryczka 69'&&el.getClientRects().length).click());
      await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(el=>el.textContent.trim()==='Pokaż na mapie'));
      await button('Pokaż na mapie');
      await page.waitForSelector('[data-map-stop-sheet]');
      await new Promise(resolve=>setTimeout(resolve,600));
    };
    await showStopOnMap();
    assert.equal(await style('.stop-highlight-pin .map-stop-pin','color'),'rgb(59, 130, 246)','selected stop follows the saved accent');
    await accent('Fioletowy');
    await page.waitForFunction(()=>getComputedStyle(document.querySelector('.stop-highlight-pin .map-stop-pin')).color==='rgb(139, 92, 246)');
    await accent('Niebieski');
    assert.equal(await page.$eval('[data-map-stop-sheet]',el=>el.dataset.glass),'on','fresh install enables glass');
    assert.equal(await page.$eval('[data-map-stop-sheet]',el=>el.dataset.expanded),'false','show on map opens compact card');
    assert.ok(await page.$eval('[data-map-stop-sheet]',el=>el.getBoundingClientRect().height)<120);
    await page.click('[aria-label="Rozwiń panel przystanku"]');
    await page.waitForFunction(()=>[...document.querySelectorAll('[data-map-stop-sheet] .map-detail-row')].some(el=>el.textContent.includes('Rzeszów')));
    await new Promise(resolve=>setTimeout(resolve,400));
    assert.ok(await page.$eval('[data-map-stop-sheet]',el=>el.getBoundingClientRect().height)<=851*0.42+1);
    const mapBefore=await page.$eval('.leaflet-map-pane',el=>el.style.transform);
    await page.mouse.move(70,330);await page.mouse.down();await page.mouse.move(160,370,{steps:12});await page.mouse.up();
    await page.waitForFunction(before=>document.querySelector('.leaflet-map-pane').style.transform!==before,{},mapBefore);
    assert.equal(await page.$eval('[data-map-stop-sheet]',el=>el.dataset.expanded),'true','panning map retains the expanded sheet');
    await screenshot('map-stop-glass-expanded');
    const handle=await page.$('[aria-label="Zwiń panel przystanku"]');const bounds=await handle.boundingBox();
    await page.mouse.move(bounds.x+bounds.width/2,bounds.y+12);await page.mouse.down();const stopExpandedHeight=await page.$eval('[data-map-stop-sheet]',el=>el.getBoundingClientRect().height);await page.mouse.move(bounds.x+bounds.width/2,bounds.y+65,{steps:10});assert.ok(await page.$eval('[data-map-stop-sheet]',el=>el.getBoundingClientRect().height)<stopExpandedHeight-20,'stop sheet follows the finger before release');await page.mouse.up();
    await page.waitForFunction(()=>document.querySelector('[data-map-stop-sheet]').dataset.expanded==='false');
    await page.evaluate(()=>{localStorage.setItem('mks_transparent','false');localStorage.setItem('mks_app_theme','dark-oled');});
    await page.reload({waitUntil:'domcontentloaded'});await openStops();await showStopOnMap();
    assert.equal(await page.$eval('[data-map-stop-sheet]',el=>el.dataset.glass),'off','saved glass preference survives reload');
    await page.click('[aria-label="Rozwiń panel przystanku"]');await screenshot('map-stop-amoled-solid');
    assert.equal(await style('[data-map-stop-sheet]','backgroundColor'),'rgb(20, 29, 38)','AMOLED surfaces use the balanced palette');
    assert.equal(await style('.pks-navigation','backgroundColor'),'rgb(20, 29, 38)','AMOLED navigation shares the surface palette');
    await page.evaluate(()=>localStorage.setItem('mks_transparent','true'));
    await page.reload({waitUntil:'domcontentloaded'});await openStops();await showStopOnMap();
    const oledGlass=await style('[data-map-stop-sheet]','backgroundColor');
    assert.equal(await style('.pks-navigation','backgroundColor'),oledGlass,'AMOLED glass is consistent between navigation and stop panel');
    await screenshot('map-stop-amoled-glass');
    await page.evaluate(()=>localStorage.setItem('mks_app_theme','dark'));
    await page.reload({waitUntil:'domcontentloaded'});await openStops();await showStopOnMap();
    assert.notEqual(await style('[data-map-stop-sheet]','backgroundColor'),oledGlass,'dark and AMOLED have distinct glass palettes');
    assert.equal(await page.$$eval('.map-stop-handle .rounded-2xl',els=>els.length),0,'stop handle retains only the title and arrow');
    await button('Opcje');await page.waitForSelector('[data-options-sheet]');await new Promise(resolve=>setTimeout(resolve,650));
    const compactHeight=await page.$eval('[data-options-sheet]',el=>el.getBoundingClientRect().height);
    const optionsHandle=await page.$('[aria-label="Rozwiń opcje"]');const optionsBounds=await optionsHandle.boundingBox();
    const handleX=optionsBounds.x+optionsBounds.width/2,handleY=optionsBounds.y+optionsBounds.height/2;
    await page.mouse.move(handleX,handleY);await page.mouse.down();await page.mouse.move(handleX,handleY-70,{steps:8});
    const draggingHeight=await page.$eval('[data-options-sheet]',el=>el.getBoundingClientRect().height);
    assert.ok(draggingHeight>compactHeight+45,'settings follow the pointer before release');
    await page.mouse.up();await page.waitForFunction(()=>document.querySelector('[data-options-sheet]').dataset.expanded==='true');
    assert.equal(await page.$$eval('[aria-label="Lżejsze efekty"]',els=>els.length),1,'performance preference appears once, below appearance');
    await page.$eval('[aria-label="Lżejsze efekty"]',el=>el.click());
    await page.waitForFunction(()=>document.querySelector('.pks-theme-root').classList.contains('pks-light-effects')&&localStorage.getItem('mks_light_effects')==='true');
    await page.$eval('[aria-label="Lżejsze efekty"]',el=>el.click());
    await page.waitForFunction(()=>!document.querySelector('.pks-theme-root').classList.contains('pks-light-effects'));
    await new Promise(resolve=>setTimeout(resolve,650));await screenshot('options-expanded');
    const expandedHeight=await page.$eval('[data-options-sheet]',el=>el.getBoundingClientRect().height);
    const collapseHandle=await page.$('[aria-label="Zwiń opcje"]');const collapseBounds=await collapseHandle.boundingBox();
    const collapseY=collapseBounds.y+collapseBounds.height/2;
    await page.mouse.move(handleX,collapseY);await page.mouse.down();await page.mouse.move(handleX,collapseY+70,{steps:8});
    assert.ok(await page.$eval('[data-options-sheet]',el=>el.getBoundingClientRect().height)<expandedHeight-45,'settings follow a downward drag before release');
    await page.mouse.up();await page.waitForFunction(()=>document.querySelector('[data-options-sheet]').dataset.expanded==='false');
    await new Promise(resolve=>setTimeout(resolve,650));await screenshot('options-compact');
    await page.mouse.click(4,4);await page.waitForSelector('[role="dialog"]',{hidden:true});
    await button('Opcje');await page.waitForSelector('[data-options-sheet]');
    await page.waitForFunction(()=>history.state?.pksBackGuard===true);
    await page.evaluate(()=>history.back());await page.waitForSelector('[data-options-sheet]',{hidden:true});
    showFixtureBus=true;
    await page.evaluate(()=>localStorage.setItem('mks_map_state',JSON.stringify({center:{lat:50.14922,lng:21.95757},zoom:12})));
    await page.reload({waitUntil:'domcontentloaded'});await page.waitForSelector('.leaflet-marker-icon.mks-bus-marker');
    assert.deepEqual(await page.$eval('.mks-bus-marker svg[data-bus-glyph]',el=>[...el.querySelectorAll('rect,circle')].map(node=>[node.tagName,...['x','y','width','height','rx','cx','cy','r'].map(key=>node.getAttribute(key))])),carrierGeometry,'map and carrier picker use exactly the same bus geometry');
    await page.evaluate(()=>document.querySelector('.leaflet-marker-icon.mks-bus-marker').click());
    await page.waitForSelector('[data-map-bus-sheet]');
    await page.waitForFunction(()=>{
      const canvas=document.querySelector('.leaflet-routeLine-pane canvas');
      if(!canvas || !canvas.width || !canvas.height)return false;
      const pixels=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data;
      let painted=0;
      for(let i=3;i<pixels.length;i+=4)if(pixels[i]>100 && ++painted>100)return true;
      return false;
    },{timeout:20000});
    assert.equal(await page.$eval('[data-map-bus-sheet]',el=>el.dataset.expanded),'false','a bus selection opens its compact panel');
    await page.click('[aria-label="Rozwiń panel autobusu"]');
    await page.waitForFunction(()=>document.querySelector('[data-map-bus-sheet]').dataset.expanded==='true');await new Promise(resolve=>setTimeout(resolve,450));const busHandle=await page.$('[aria-label="Zwiń panel autobusu"]');const busBounds=await busHandle.boundingBox();const busHeight=await page.$eval('[data-map-bus-sheet]',el=>el.getBoundingClientRect().height);await page.mouse.move(busBounds.x+30,busBounds.y+12);await page.mouse.down();await page.mouse.move(busBounds.x+30,busBounds.y+62,{steps:8});assert.ok(await page.$eval('[data-map-bus-sheet]',el=>el.getBoundingClientRect().height)<busHeight-20,'bus sheet follows finger');await page.mouse.up();await page.waitForFunction(()=>document.querySelector('[data-map-bus-sheet]').dataset.expanded==='false');await page.click('[aria-label="Rozwiń panel autobusu"]');
    await page.evaluate(()=>document.querySelector('.leaflet-marker-icon.mks-bus-marker').click());
    await page.waitForFunction(()=>document.querySelector('[data-map-bus-sheet]').dataset.expanded==='false');
    await screenshot('bus-compact');
    await page.waitForFunction(()=>history.state?.pksBackGuard===true);
    await page.evaluate(()=>history.back());await page.waitForSelector('[data-map-bus-sheet]',{hidden:true});
    fixtureBus=structuredClone(require('./fixtures/pks-251-107-2026-10-08.json'));
    fixtureBus.position.position_date='2026-10-06 14:18:30';fixtureBus.journey.vehicle_journey_date='2026-10-06';
    fixtureBus.journey.departure_time='14:15:00';
    fixtureBus.next_stop_points=fixtureBus.next_stop_points.map((stop,index)=>({...stop,planned_departure_time:`2026-10-06 14:${String(25+index).padStart(2,'0')}:00`,real_departure_time:`2026-10-06 14:${String(25+index).padStart(2,'0')}:00`}));
    await page.evaluate(()=>localStorage.setItem('mks_map_state',JSON.stringify({center:{lat:49.925,lng:21.963},zoom:12})));
    await page.reload({waitUntil:'domcontentloaded'});await page.waitForSelector('.leaflet-marker-icon.mks-bus-marker');
    await page.evaluate(()=>document.querySelector('.leaflet-marker-icon.mks-bus-marker').click());await page.waitForSelector('[data-map-bus-sheet]');
    assert.match(await page.$eval('[data-map-bus-sheet]',el=>el.textContent),/251/);
    await page.waitForFunction(()=>{
      const canvas=document.querySelector('.leaflet-routeLine-pane canvas');if(!canvas?.width||!canvas?.height)return false;
      const pixels=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data;
      let painted=0;for(let i=3;i<pixels.length;i+=4)if(pixels[i]>100&&++painted>100)return true;return false;
    },{timeout:20000});
    await screenshot('pks-251-107-route');
    showFixtureBus=false;showMarcel=true;
    await page.evaluate(()=>{localStorage.setItem('mks_transport_providers',JSON.stringify(['marcel']));localStorage.setItem('mks_map_state',JSON.stringify({center:{lat:49.95,lng:21.88},zoom:12}));});
    await page.reload({waitUntil:'domcontentloaded'});await page.waitForSelector('.leaflet-marker-icon.mks-bus-marker');
    await page.evaluate(()=>document.querySelector('.leaflet-marker-icon.mks-bus-marker').click());await page.waitForSelector('[data-map-bus-sheet]');
    assert.match(await page.$eval('[data-map-bus-sheet]',el=>el.textContent),/Rzeszów/);
    await page.waitForFunction(()=>{const canvas=document.querySelector('.leaflet-routeLine-pane canvas');if(!canvas?.width||!canvas?.height)return false;const pixels=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data;let painted=0;for(let i=3;i<pixels.length;i+=4)if(pixels[i]>100&&++painted>100)return true;return false;},{timeout:20000});
    assert.equal(marcelSecondary,marcelRoad.chunks.length,'disconnected real Marcel chunks must be rebuilt before painting');
    await screenshot('marcel-jaslo-rzeszow-route');
    await page.goto(`${origin}/maintenance/`,{waitUntil:'domcontentloaded'});await page.waitForSelector('[data-transport-diagnostics]');
    await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(el=>el.textContent.trim()==='Dodaj'&&!el.disabled));
    await button('Dodaj');
    await page.waitForFunction(()=>document.querySelector('[aria-label="Adres API"]').value==='');
    await page.click('[aria-label="Nazwa endpointu"]',{clickCount:3});await page.type('[aria-label="Nazwa endpointu"]','Backup UI');
    await page.type('[aria-label="Adres API"]','https://backup.example');
    await button('Testuj ponownie');
    await page.waitForFunction(()=>window.__maintenanceCalls.some(call=>call.name==='testMaintenanceEndpoint'&&call.data.url==='https://backup.example'));
    await page.waitForFunction(()=>[...document.querySelectorAll('[role="status"]')].some(el=>el.textContent.includes('Połączenie z API działa')));
    await button('Zapisz zmiany');
    await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(el=>el.textContent.trim()==='Ustaw jako aktywny'&&!el.disabled));
    await button('Ustaw jako aktywny');
    await page.waitForFunction(()=>window.__maintenanceCalls.some(call=>call.name==='setActiveMaintenanceEndpoint'&&call.data.endpointId==='created-endpoint'));
    await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(el=>el.textContent.trim()==='Przywróć poprzedni endpoint'&&!el.disabled));
    await button('Przywróć poprzedni endpoint');
    await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(el=>el.textContent.trim()==='Wyłącz endpoint'&&!el.disabled));
    await button('Wyłącz endpoint');
    await page.waitForFunction(()=>[...document.querySelectorAll('label')].some(el=>el.textContent.includes('Endpoint włączony')&&!el.querySelector('input').checked));
    await page.evaluate(()=>[...document.querySelectorAll('label')].find(el=>el.textContent.includes('Endpoint włączony')).querySelector('input').click());
    await button('Zapisz zmiany');
    await page.waitForFunction(()=>window.__maintenanceCalls.some(call=>call.name==='saveMaintenanceEndpoint'&&call.data.endpoint.id==='created-endpoint'&&call.data.endpoint.enabled));
    await screenshot('maintenance-mobile');
    await button('Historia zmian');await page.waitForFunction(()=>document.body.innerText.includes('rollbackMaintenanceEndpoint'));
    const fitDialog=async()=>{
      await page.waitForSelector('.admin-modal-overlay');await new Promise(resolve=>setTimeout(resolve,450));
      const box=await page.evaluate(()=>{const overlay=document.querySelector('.admin-modal-overlay'),card=overlay.firstElementChild,r=card.getBoundingClientRect();return {top:r.top,bottom:r.bottom,left:r.left,right:r.right,height:innerHeight,width:innerWidth};});
      assert.ok(box.top>=10&&box.bottom<=box.height-10,JSON.stringify(box));assert.ok(box.left>=10&&box.right<=box.width-10,JSON.stringify(box));
    };
    await fitDialog();
    assert.equal(await page.evaluate(()=>[...document.querySelectorAll('.admin-modal-overlay div')].some(el=>el.scrollWidth>el.clientWidth+1)),false,'History must fit long endpoint and action names');
    await screenshot('admin-history-mobile');
    await button('Wyczyść historię');await page.waitForFunction(()=>document.body.innerText.includes('Potwierdź usunięcie historii'));
    await button('Anuluj');assert.ok(await page.$eval('.admin-modal-overlay',el=>el.innerText.includes('rollbackMaintenanceEndpoint')));
    await button('Wyczyść historię');await button('Potwierdź usunięcie historii');
    await page.waitForFunction(()=>document.querySelector('.admin-modal-overlay').innerText.includes('Brak historii zmian.'));
    assert.ok(await page.evaluate(()=>window.__maintenanceCalls.some(call=>call.name==='clearMaintenanceHistory')));
    await page.goto(`${origin}/dialog-fixture/`,{waitUntil:'domcontentloaded'});
    await fitDialog();
    const shield=await page.evaluate(()=>{const el=document.querySelector('.admin-modal-overlay .lucide-shield');const r=el.getBoundingClientRect(),parent=el.parentElement.getBoundingClientRect();return {w:r.width,h:r.height,pw:parent.width,ph:parent.height};});
    assert.equal(shield.w,24);assert.equal(shield.h,24);assert.equal(shield.pw,shield.ph);
    const checkSave=async()=>{const result=await page.evaluate(()=>{const buttons=[...document.querySelectorAll('.admin-modal-overlay button')];const b=buttons.find(el=>el.textContent.trim()==='Zapisz zmiany'),r=b.getBoundingClientRect();return {top:r.top,bottom:r.bottom,height:innerHeight,covered:document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)!==b};});assert.ok(result.top>=0&&result.bottom<=result.height,JSON.stringify(result));assert.equal(result.covered,false);};
    await checkSave();await screenshot('admin-roles-mobile');
    await page.setViewport({width:320,height:568,deviceScaleFactor:1,isMobile:true,hasTouch:true});await fitDialog();await checkSave();
    await page.setViewport({width:393,height:400,deviceScaleFactor:1,isMobile:true,hasTouch:true});await fitDialog();await checkSave();await screenshot('admin-roles-keyboard-height');
    await button('Zapisz zmiany');await page.waitForFunction(()=>!document.querySelector('.admin-modal-overlay'));await button('Ban');await fitDialog();
    await page.evaluate(()=>{const body=document.querySelector('.admin-modal-overlay .overflow-y-auto');body.scrollTop=body.scrollHeight;});
    await button('ZABLOKUJ URZĄDZENIE');await page.waitForFunction(()=>!document.querySelector('.admin-modal-overlay'));
    console.log('Browser: real role, ban and history dialogs escape transformed parents, fit small phones and keyboard height, stay above navigation and keep the shield square.');
    await page.evaluateOnNewDocument(()=>{const original=window.setTimeout.bind(window);window.setTimeout=((callback,delay,...args)=>original(callback,delay===30000?100:delay,...args));});
    await page.goto(`${origin}/startup-fixture/`,{waitUntil:'domcontentloaded'});
    await page.waitForFunction(()=>document.body.innerText.includes('Przekroczono czas połączenia'));
    await page.waitForSelector('[data-restored-role="owner"]');
    assert.ok(await page.$eval('[data-restored-role]',el=>el.innerText.includes('owner')));
    assert.equal(await page.evaluate(()=>document.body.innerText.includes('Przekroczono czas połączenia')),false);
    await page.evaluate(()=>window.__startupTest.grants());
    await page.waitForFunction(()=>window.__startupTest.profile()?.role==='admin');
    assert.deepEqual(await page.evaluate(()=>window.__startupTest.profile().permissions),{monitor:true,canBan:false});
    const profileWrites=await page.evaluate(()=>window.__startupTest.writes());await page.evaluate(()=>window.__startupTest.heartbeat());
    assert.equal(await page.evaluate(()=>window.__startupTest.writes()),profileWrites,'heartbeats must not overwrite saved grants');
    await page.evaluate(()=>window.__startupTest.deleteDevice());
    await page.waitForSelector('[data-restored-role="user"]');
    assert.equal(await page.evaluate(()=>window.__startupTest.profile()?.role),'user','deleted administrator re-registers without the revoked rank');
    assert.equal(await page.evaluate(()=>window.__startupTest.profile()?.verified),false);
    console.log('Browser: deleting both admin device and installation revokes admin immediately and re-registers as an unverified user without a stuck loading screen.');
    console.log('Browser: real FirebaseProvider recovers after startup deadline and restores owner despite old Firestore rules without reload or downgrade.');
    await page.setViewport({width:393,height:851,deviceScaleFactor:1});
    await page.evaluate(()=>localStorage.setItem('pks-live:api-statistics:v1',JSON.stringify({version:1,startedAt:Date.now(),days:[{date:'2026-10-06',providers:{pks:{requests:80,errors:2,latencyMs:16000},mpk_rzeszow:{requests:15,errors:1,latencyMs:3000},marcel:{requests:5,errors:0,latencyMs:1000}}}]})));
    await page.goto(`${origin}/statistics-fixture/`,{waitUntil:'domcontentloaded'});
    await page.waitForSelector('[data-statistics-fixture-ready="true"]');
    await button('Otwórz menu testowe');await page.waitForFunction(()=>{const r=document.querySelector('nav button:nth-child(2)').getBoundingClientRect();return r.left>=0&&r.right<=innerWidth;});await page.click('nav button:nth-child(2)');await page.waitForSelector('[data-statistics-view]');
    await page.waitForFunction(()=>document.querySelector('[data-statistic="Zapytania API"]').textContent==='100');
    assert.equal(await page.$eval('[data-statistic="Nowe urządzenia"]',el=>el.textContent),'2');
    assert.equal(await page.$eval('[data-statistic="Aktywne urządzenia"]',el=>el.textContent),'2');
    assert.equal(await page.$eval('[data-statistic="Skuteczność API"]',el=>el.textContent),'97%');
    const statisticsFits=async()=>assert.equal(await page.$eval('[data-statistics-view]',el=>el.scrollWidth>el.clientWidth+1),false,'Statistics must fit without horizontal overflow');
    await statisticsFits();await screenshot('statistics-dark-mobile');
    await button('90 dni');assert.equal(await page.$$eval('[data-statistics-chart="requests"] rect[role="button"]',nodes=>nodes.length),90);
    await button('Dzisiaj');assert.equal(await page.$$eval('[data-statistics-chart="installations"] rect[role="button"]',nodes=>nodes.length),1);
    await button('7 dni');
    await page.evaluate(()=>{URL.createObjectURL=blob=>{blob.text().then(text=>window.__statisticsCsv=text);return 'blob:test-statistics';};HTMLAnchorElement.prototype.click=()=>{};});
    await button('Eksport CSV');await page.waitForFunction(()=>window.__statisticsCsv);
    const csv=await page.evaluate(()=>window.__statisticsCsv);assert.match(csv,/2026-10-06;2;100;3/);assert.ok(!csv.includes('same'));
    await button('Zmień motyw testowy');await statisticsFits();await screenshot('statistics-light-mobile');
    await page.setViewport({width:320,height:568,deviceScaleFactor:1});await statisticsFits();await screenshot('statistics-small-phone');
    await page.setViewport({width:1440,height:1000,deviceScaleFactor:1});await statisticsFits();await screenshot('statistics-desktop');
    await page.click('nav button:first-child');await page.waitForFunction(()=>!document.querySelector('[data-statistics-view]'));
    await page.click('nav button:nth-child(2)');await page.waitForSelector('[data-statistics-view]');
    console.log('Browser: statistics navigation, unique installations, local API totals, date ranges, CSV, light/dark and 320px mobile layouts passed without backend writes.');
    assert.deepEqual(errors,[]);
    console.log('Browser: accent changes list, departures, favourites and controls; carrier colours survive; reload persists; light/dark mobile layout has no horizontal overflow.');
    console.log('Browser: default glass, compact map stop card, limited expanded height, map panning, handle swipe, saved glass preference and brighter AMOLED surfaces passed.');
    console.log('Browser: full list replaces the preview, 40 and 80 cards do not overlap, scrolling works, closing restores position, and map and carrier SVG geometry is identical.');
    console.log('Browser: fresh install defaults to AMOLED; saved themes survive; carrier selection uses three SVG buses with functional selection and no overflow.');
    console.log('Browser: real maintenance controls add a draft, test its URL, retain the saved ID, activate, roll back, disable, re-enable and display history. Firebase calls use a fixture adapter; backend behaviour is tested separately.');
    console.log('Browser: favourites animate their position, departure spacing is compact, the new pin follows accent, settings track upward and downward dragging before release, backdrop dismisses, and bus panels default to collapsed.');
  }catch(error){await page.screenshot({path:'test/ui-previews/failure.png'}).catch(()=>{});console.error(await page.evaluate(()=>document.body.innerText).catch(()=>''));console.error(await page.evaluate(()=>[...document.querySelectorAll('.transit-view,.transit-stop-card,.transit-stop-card button')].map(el=>({tag:el.tagName,rect:el.getBoundingClientRect().toJSON(),display:getComputedStyle(el).display}))).catch(()=>[]));console.error('Page errors:',errors);throw error;}
  finally{await browser.close();await new Promise(resolve=>server.close(resolve));fixture.cleanup();}
})().catch(error=>{console.error(error);server.close();fixture.cleanup();process.exitCode=1;});
