const assert=require('node:assert/strict');
const http=require('node:http');const fs=require('node:fs');const path=require('node:path');
const puppeteer=require('puppeteer');
const fixture=require('./build-accent-fixture.cjs')();const root=fixture.root;const productionRoot=path.resolve('out');
const server=http.createServer((req,res)=>{
  const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);
  let file=path.resolve(root,'.'+(pathname.endsWith('/')?`${pathname}index.html`:pathname));
  if(!file.startsWith(root+path.sep)){res.writeHead(404);res.end();return;}
  if(!fs.existsSync(file))file=path.resolve(productionRoot,'.'+pathname);
  if(!file.startsWith(productionRoot+path.sep)&&!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);res.end();return;}
  const type={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.webp':'image/webp'}[path.extname(file)]||'application/octet-stream';
  res.setHeader('Content-Type',type);fs.createReadStream(file).pipe(res);
});
(async()=>{
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  const origin=`http://127.0.0.1:${server.address().port}`;
  const browser=await puppeteer.launch({headless:true,executablePath:process.env.CHROME_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage']});
  const page=await browser.newPage();const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  fs.mkdirSync('test/ui-previews',{recursive:true});
  try{
    await page.setViewport({width:393,height:851,deviceScaleFactor:1});
    await page.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'no-preference'}]);
    await page.evaluateOnNewDocument(()=>{
      const Original=Date;const now=Original.parse('2026-10-06T12:18:30Z');
      window.Date=class extends Original {constructor(...args){super(...(args.length?args:[now]));}static now(){return now;}};
    });
    await page.setRequestInterception(true);
    let showFixtureBus=false;
    const fixtureBus=structuredClone(require('./fixtures/pks-vehicle.json'));
    fixtureBus.position.position_date='2026-10-06 14:18:30';
    fixtureBus.journey.vehicle_journey_date='2026-10-06';fixtureBus.journey.departure_time='14:25:00';
    fixtureBus.next_stop_points=fixtureBus.next_stop_points.map((stop,index)=>({...stop,planned_departure_time:`2026-10-06 14:${String(25+index*2).padStart(2,'0')}:00`,real_departure_time:`2026-10-06 14:${String(25+index*2).padStart(2,'0')}:00`}));
    page.on('request',async request=>{
      const url=request.url();
      const json=data=>request.respond({status:200,contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:JSON.stringify(data)});
      if(url.includes('stop-point-timetable'))return json({success:true,items:[{line_name:'108',description:'Rzeszów',journeys:[{journey_id:1,time:'14:21',stop_point_code:'69',legends:['D']}]}]});
      if(url.includes('/pks/get_vehicles.php'))return json(showFixtureBus?[fixtureBus]:[]);
      if(url.endsWith('/api/pks/vehicles'))return json({items:[]});
      if(url.includes('/api/pks/einfo/stop-point'))return json({items:[]});
      if(url.includes('mpkrzeszow.pl')||url.includes('api-site.marcel-bus.pl'))return json([]);
      if(url.startsWith(origin))return request.continue();
      return request.abort();
    });
    const button=async label=>page.evaluate(text=>[...document.querySelectorAll('button')].find(el=>el.textContent.trim()===text)?.click(),label);
    const visible=async selector=>{
      await page.waitForFunction(css=>[...document.querySelectorAll(css)].some(el=>{const r=el.getBoundingClientRect();return r.width>0&&r.height>0&&r.right>0&&r.left<innerWidth&&r.bottom>0&&r.top<innerHeight;}),{},selector);
      const handle=await page.evaluateHandle(css=>[...document.querySelectorAll(css)].find(el=>{const r=el.getBoundingClientRect();return r.width>0&&r.height>0&&r.right>0&&r.left<innerWidth&&r.bottom>0&&r.top<innerHeight;}),selector);
      return handle.asElement();
    };
    const style=async(selector,property)=>(await visible(selector)).evaluate((el,key)=>getComputedStyle(el)[key],property);
    const openStops=async()=>{
      console.log('Opening stops');
      await page.waitForFunction(()=>document.documentElement.style.getPropertyValue('--pks-accent').trim()!=='');
      await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(el=>el.textContent.trim()==='Przystanki'));
      await button('Przystanki');await page.waitForSelector('input[placeholder*="Babica"]');
      await page.type('input[placeholder*="Babica"]','Baryczka');
      await page.waitForFunction(()=>[...document.querySelectorAll('h3')].some(el=>el.textContent==='Baryczka 69'));
      await new Promise(resolve=>setTimeout(resolve,450));
    };
    const accent=async name=>{
      console.log('Selecting accent:',name);
      await button('Opcje');await page.waitForSelector('[role="dialog"]');
      await page.click(`[aria-label="Kolor akcentu: ${name}"]`);
      await page.mouse.click(4,4);await page.waitForSelector('[role="dialog"]',{hidden:true});
    };
    const overflow=async()=>assert.equal(await page.evaluate(()=>[...document.querySelectorAll('.transit-view')].some(el=>el.scrollWidth>el.clientWidth+1)),false);
    const screenshot=async name=>{await new Promise(resolve=>setTimeout(resolve,450));return page.screenshot({path:`test/ui-previews/${name}.png`});};
    await page.goto(origin,{waitUntil:'domcontentloaded'});
    console.log('App loaded');
    await page.waitForFunction(()=>document.documentElement.style.getPropertyValue('--pks-accent').trim()!=='');
    await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(el=>el.textContent.trim()==='Opcje'));
    await page.waitForSelector('[data-ui-theme="dark-oled"]');
    assert.equal(await page.evaluate(()=>localStorage.getItem('mks_app_theme')),null,'AMOLED is the default without overwriting a saved preference');
    await page.click('[aria-label="Przewoźnicy"]');await page.waitForSelector('[data-carrier-grid]');
    assert.equal(await page.$$eval('[data-carrier-grid] img',els=>els.length),0,'bus selection uses no raster artwork');
    assert.equal(await page.$$eval('[data-carrier-bus-svg]',els=>els.length),3);
    const carrierGeometry=await page.$eval('[data-carrier-grid] button[aria-label="PKS Rzeszów"] svg',el=>[...el.querySelectorAll('rect,circle')].map(node=>[node.tagName,...['x','y','width','height','rx','cx','cy','r'].map(key=>node.getAttribute(key))]));
    const pksSelected=await page.$eval('[data-carrier-grid] button[aria-label="PKS Rzeszów"]',el=>el.getAttribute('aria-pressed'));
    await page.click('[data-carrier-grid] button[aria-label="PKS Rzeszów"]');
    assert.notEqual(await page.$eval('[data-carrier-grid] button[aria-label="PKS Rzeszów"]',el=>el.getAttribute('aria-pressed')),pksSelected);
    await page.click('[data-carrier-grid] button[aria-label="PKS Rzeszów"]');
    assert.ok(await page.$eval('[data-carrier-grid]',el=>el.scrollWidth<=el.clientWidth+1));
    await screenshot('carriers-amoled');await page.click('[aria-label="Zamknij panel przewoźników"]');
    await page.evaluate(()=>localStorage.setItem('mks_app_theme','dark'));await page.reload({waitUntil:'domcontentloaded'});
    await page.waitForSelector('[data-ui-theme="dark"]');
    await accent('Fioletowy');
    await button('Przystanki');
    await page.waitForFunction(()=>document.querySelectorAll('[data-stop-card-id]').length>=3);
    await page.evaluate(()=>{const button=[...document.querySelectorAll('button')].find(el=>el.textContent.trim().startsWith('Pokaż wszystkie ('));button.scrollIntoView();});
    const previewScroll=await page.$eval('[data-stop-list-scroll]',el=>el.scrollTop);
    await page.evaluate(()=>[...document.querySelectorAll('button')].find(el=>el.textContent.trim().startsWith('Pokaż wszystkie (')).click());
    await page.waitForSelector('[data-stop-list-mode="full"]');
    await new Promise(resolve=>setTimeout(resolve,450));
    assert.equal(await page.$$eval('[data-stop-list-scroll]',els=>els.length),1,'full view replaces the preview scroll container');
    assert.equal(await page.$$eval('input[placeholder*="Babica"]',els=>els.length),1,'full view has no preview header underneath');
    const assertCards=async()=>assert.equal(await page.$$eval('[data-stop-card-id]',cards=>cards.every((card,index)=>{
      const bounds=card.getBoundingClientRect();const next=cards[index+1]?.getBoundingClientRect();
      return bounds.height>=70&&(!next||bounds.bottom<=next.top+1);
    })),true,'full stop cards retain their height and never overlap');
    await assertCards();assert.equal(await page.$$eval('[data-stop-card-id]',els=>els.length),40);
    await screenshot('stops-full-glass');
    await page.evaluate(()=>[...document.querySelectorAll('button')].find(el=>el.textContent.trim().startsWith('Pokaż więcej (')).click());
    await page.waitForFunction(()=>document.querySelectorAll('[data-stop-card-id]').length===80);await assertCards();
    await page.$eval('[data-stop-list-scroll]',el=>{el.scrollTop=500;});
    assert.ok(await page.$eval('[data-stop-list-scroll]',el=>el.scrollTop)>=499,'full list scrolls independently');
    await page.click('[aria-label="Zamknij pełną listę przystanków"]');
    await page.waitForSelector('[data-stop-list-mode="preview"]');
    assert.equal(await page.$$eval('[data-stop-card-id]',els=>els.length),30);
    assert.ok(Math.abs(await page.$eval('[data-stop-list-scroll]',el=>el.scrollTop)-previewScroll)<2,'closing restores the previous scroll position');
    await page.$eval('[data-stop-list-scroll]',el=>{el.scrollTop=0;});
    const favorite=await page.evaluate(()=>{const card=document.querySelectorAll('[data-stop-card-id]')[2];return {id:card.dataset.stopCardId,top:card.getBoundingClientRect().top};});
    await page.evaluate(id=>document.querySelector(`[data-stop-card-id="${id}"] [aria-label="Dodaj do ulubionych"]`).click(),favorite.id);
    await page.waitForFunction(id=>{const card=document.querySelector(`[data-stop-card-id="${id}"]`);return card.style.transform&&card.style.transform!=='none';},{},favorite.id);
    await new Promise(resolve=>setTimeout(resolve,650));
    assert.ok(await page.evaluate(id=>document.querySelector(`[data-stop-card-id="${id}"]`).getBoundingClientRect().top,favorite.id)<favorite.top-20,'favourite card moves smoothly to the top');
    await openStops();
    await page.waitForFunction(()=>getComputedStyle(document.documentElement).getPropertyValue('--pks-accent').trim()==='#8b5cf6');
    const brandBefore=await style('.transit-stop-card .text-teal-400','color');
    const before=await style('.transit-stop-card .ui-accent-soft','backgroundColor');
    await (await visible('.transit-stop-card [aria-label="Dodaj do ulubionych"]')).click();await visible('.transit-stop-card .ui-accent-fill');
    await overflow();await screenshot('stops-dark-purple');
    await page.evaluate(()=>[...document.querySelectorAll('h3')].find(el=>el.textContent==='Baryczka 69'&&el.getClientRects().length).click());
    await page.waitForSelector('button[data-selected="true"]');
    await page.waitForFunction(()=>document.querySelector('.transit-view').innerText.includes('Rzeszów'));
    assert.equal(await style('.transit-view button.ui-accent-solid','backgroundColor'),'rgb(139, 92, 246)');
    await overflow();await screenshot('departures-dark-purple');
    assert.ok(await page.$eval('.transit-view',el=>parseFloat(getComputedStyle(el).paddingBottom))<=90,'departure detail has one compact bottom inset');
    assert.equal(await page.$eval('[data-stop-lines]',el=>parseFloat(getComputedStyle(el).paddingBottom)),0,'line badges do not add a second spacer');
    await accent('Niebieski');
    assert.equal(await style('.transit-view button.ui-accent-solid','backgroundColor'),'rgb(59, 130, 246)');
    await (await visible('[aria-label="Wróć do listy przystanków"]')).click();
    const after=await style('.transit-stop-card .ui-accent-soft','backgroundColor');
    assert.notEqual(before,after);
    assert.equal(await style('.transit-stop-card .text-teal-400','color'),brandBefore);
    await page.evaluate(()=>localStorage.setItem('mks_app_theme','light'));
    await page.reload({waitUntil:'domcontentloaded'});await openStops();
    await page.waitForFunction(()=>getComputedStyle(document.documentElement).getPropertyValue('--pks-accent').trim()==='#3b82f6');
    assert.equal(await page.$eval('.transit-view',el=>el.dataset.uiMode),'light');
    await overflow();await screenshot('stops-light-blue');
    const showStopOnMap=async()=>{
      await page.evaluate(()=>[...document.querySelectorAll('h3')].find(el=>el.textContent==='Baryczka 69'&&el.getClientRects().length).click());
      await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(el=>el.textContent.trim()==='Pokaż na mapie'));
      await button('Pokaż na mapie');
      await page.waitForSelector('[data-map-stop-sheet]');
      await new Promise(resolve=>setTimeout(resolve,600));
    };
    await showStopOnMap();
    assert.equal(await style('.stop-highlight-pin .map-stop-pin','color'),'rgb(59, 130, 246)','selected stop follows the saved accent');
    await accent('Fioletowy');
    await page.waitForFunction(()=>getComputedStyle(document.querySelector('.stop-highlight-pin .map-stop-pin')).color==='rgb(139, 92, 246)');
    await accent('Niebieski');
    assert.equal(await page.$eval('[data-map-stop-sheet]',el=>el.dataset.glass),'on','fresh install enables glass');
    assert.equal(await page.$eval('[data-map-stop-sheet]',el=>el.dataset.expanded),'false','show on map opens compact card');
    assert.ok(await page.$eval('[data-map-stop-sheet]',el=>el.getBoundingClientRect().height)<120);
    await page.click('[aria-label="Rozwiń panel przystanku"]');
    await page.waitForFunction(()=>[...document.querySelectorAll('[data-map-stop-sheet] .map-detail-row')].some(el=>el.textContent.includes('Rzeszów')));
    await new Promise(resolve=>setTimeout(resolve,400));
    assert.ok(await page.$eval('[data-map-stop-sheet]',el=>el.getBoundingClientRect().height)<=851*0.42+1);
    const mapBefore=await page.$eval('.leaflet-map-pane',el=>el.style.transform);
    await page.mouse.move(70,330);await page.mouse.down();await page.mouse.move(160,370,{steps:12});await page.mouse.up();
    await page.waitForFunction(before=>document.querySelector('.leaflet-map-pane').style.transform!==before,{},mapBefore);
    assert.equal(await page.$eval('[data-map-stop-sheet]',el=>el.dataset.expanded),'true','panning map retains the expanded sheet');
    await screenshot('map-stop-glass-expanded');
    const handle=await page.$('[aria-label="Zwiń panel przystanku"]');const bounds=await handle.boundingBox();
    await page.mouse.move(bounds.x+bounds.width/2,bounds.y+12);await page.mouse.down();await page.mouse.move(bounds.x+bounds.width/2,bounds.y+65,{steps:10});await page.mouse.up();
    await page.waitForFunction(()=>document.querySelector('[data-map-stop-sheet]').dataset.expanded==='false');
    await page.evaluate(()=>{localStorage.setItem('mks_transparent','false');localStorage.setItem('mks_app_theme','dark-oled');});
    await page.reload({waitUntil:'domcontentloaded'});await openStops();await showStopOnMap();
    assert.equal(await page.$eval('[data-map-stop-sheet]',el=>el.dataset.glass),'off','saved glass preference survives reload');
    await page.click('[aria-label="Rozwiń panel przystanku"]');await screenshot('map-stop-amoled-solid');
    assert.equal(await style('[data-map-stop-sheet]','backgroundColor'),'rgb(20, 29, 38)','AMOLED surfaces use the balanced palette');
    assert.equal(await style('.pks-navigation','backgroundColor'),'rgb(20, 29, 38)','AMOLED navigation shares the surface palette');
    await page.evaluate(()=>localStorage.setItem('mks_transparent','true'));
    await page.reload({waitUntil:'domcontentloaded'});await openStops();await showStopOnMap();
    const oledGlass=await style('[data-map-stop-sheet]','backgroundColor');
    assert.equal(await style('.pks-navigation','backgroundColor'),oledGlass,'AMOLED glass is consistent between navigation and stop panel');
    await screenshot('map-stop-amoled-glass');
    await page.evaluate(()=>localStorage.setItem('mks_app_theme','dark'));
    await page.reload({waitUntil:'domcontentloaded'});await openStops();await showStopOnMap();
    assert.notEqual(await style('[data-map-stop-sheet]','backgroundColor'),oledGlass,'dark and AMOLED have distinct glass palettes');
    assert.equal(await page.$$eval('.map-stop-handle .rounded-2xl',els=>els.length),0,'stop handle retains only the title and arrow');
    await button('Opcje');await page.waitForSelector('[data-options-sheet]');await new Promise(resolve=>setTimeout(resolve,450));
    const compactHeight=await page.$eval('[data-options-sheet]',el=>el.getBoundingClientRect().height);
    const optionsHandle=await page.$('[aria-label="Rozwiń opcje"]');const optionsBounds=await optionsHandle.boundingBox();
    const handleX=optionsBounds.x+optionsBounds.width/2,handleY=optionsBounds.y+optionsBounds.height/2;
    await page.mouse.move(handleX,handleY);await page.mouse.down();await page.mouse.move(handleX,handleY-70,{steps:8});
    const draggingHeight=await page.$eval('[data-options-sheet]',el=>el.getBoundingClientRect().height);
    assert.ok(draggingHeight>compactHeight+45,'settings follow the pointer before release');
    await page.mouse.up();await page.waitForFunction(()=>document.querySelector('[data-options-sheet]').dataset.expanded==='true');
    await new Promise(resolve=>setTimeout(resolve,450));await screenshot('options-expanded');
    const expandedHeight=await page.$eval('[data-options-sheet]',el=>el.getBoundingClientRect().height);
    const collapseHandle=await page.$('[aria-label="Zwiń opcje"]');const collapseBounds=await collapseHandle.boundingBox();
    const collapseY=collapseBounds.y+collapseBounds.height/2;
    await page.mouse.move(handleX,collapseY);await page.mouse.down();await page.mouse.move(handleX,collapseY+70,{steps:8});
    assert.ok(await page.$eval('[data-options-sheet]',el=>el.getBoundingClientRect().height)<expandedHeight-45,'settings follow a downward drag before release');
    await page.mouse.up();await page.waitForFunction(()=>document.querySelector('[data-options-sheet]').dataset.expanded==='false');
    await new Promise(resolve=>setTimeout(resolve,450));await screenshot('options-compact');
    await page.mouse.click(4,4);await page.waitForSelector('[role="dialog"]',{hidden:true});
    showFixtureBus=true;
    await page.evaluate(()=>localStorage.setItem('mks_map_state',JSON.stringify({center:{lat:50.14922,lng:21.95757},zoom:12})));
    await page.reload({waitUntil:'domcontentloaded'});await page.waitForSelector('.leaflet-marker-icon.mks-bus-marker');
    assert.deepEqual(await page.$eval('.mks-bus-marker svg[data-bus-glyph]',el=>[...el.querySelectorAll('rect,circle')].map(node=>[node.tagName,...['x','y','width','height','rx','cx','cy','r'].map(key=>node.getAttribute(key))])),carrierGeometry,'map and carrier picker use exactly the same bus geometry');
    await page.evaluate(()=>document.querySelector('.leaflet-marker-icon.mks-bus-marker').click());
    await page.waitForSelector('[data-map-bus-sheet]');
    assert.equal(await page.$eval('[data-map-bus-sheet]',el=>el.dataset.expanded),'false','a bus selection opens its compact panel');
    await page.click('[aria-label="Rozwiń panel autobusu"]');
    await page.waitForFunction(()=>document.querySelector('[data-map-bus-sheet]').dataset.expanded==='true');
    await page.evaluate(()=>document.querySelector('.leaflet-marker-icon.mks-bus-marker').click());
    await page.waitForFunction(()=>document.querySelector('[data-map-bus-sheet]').dataset.expanded==='false');
    await screenshot('bus-compact');
    await page.goto(`${origin}/maintenance/`,{waitUntil:'domcontentloaded'});
    await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(el=>el.textContent.trim()==='Dodaj'&&!el.disabled));
    await button('Dodaj');
    await page.waitForFunction(()=>document.querySelector('[aria-label="Adres API"]').value==='');
    await page.click('[aria-label="Nazwa endpointu"]',{clickCount:3});await page.type('[aria-label="Nazwa endpointu"]','Backup UI');
    await page.type('[aria-label="Adres API"]','https://backup.example');
    await button('Testuj ponownie');
    await page.waitForFunction(()=>window.__maintenanceCalls.some(call=>call.name==='testMaintenanceEndpoint'&&call.data.url==='https://backup.example'));
    await page.waitForFunction(()=>[...document.querySelectorAll('[role="status"]')].some(el=>el.textContent.includes('Połączenie z API działa')));
    await button('Zapisz zmiany');
    await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(el=>el.textContent.trim()==='Ustaw jako aktywny'&&!el.disabled));
    await button('Ustaw jako aktywny');
    await page.waitForFunction(()=>window.__maintenanceCalls.some(call=>call.name==='setActiveMaintenanceEndpoint'&&call.data.endpointId==='created-endpoint'));
    await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(el=>el.textContent.trim()==='Przywróć poprzedni endpoint'&&!el.disabled));
    await button('Przywróć poprzedni endpoint');
    await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(el=>el.textContent.trim()==='Wyłącz endpoint'&&!el.disabled));
    await button('Wyłącz endpoint');
    await page.waitForFunction(()=>[...document.querySelectorAll('label')].some(el=>el.textContent.includes('Endpoint włączony')&&!el.querySelector('input').checked));
    await page.evaluate(()=>[...document.querySelectorAll('label')].find(el=>el.textContent.includes('Endpoint włączony')).querySelector('input').click());
    await button('Zapisz zmiany');
    await page.waitForFunction(()=>window.__maintenanceCalls.some(call=>call.name==='saveMaintenanceEndpoint'&&call.data.endpoint.id==='created-endpoint'&&call.data.endpoint.enabled));
    await screenshot('maintenance-mobile');
    await button('Historia zmian');await page.waitForFunction(()=>document.body.innerText.includes('rollbackMaintenanceEndpoint'));
    assert.deepEqual(errors,[]);
    console.log('Browser: accent changes list, departures, favourites and controls; carrier colours survive; reload persists; light/dark mobile layout has no horizontal overflow.');
    console.log('Browser: default glass, compact map stop card, limited expanded height, map panning, handle swipe, saved glass preference and brighter AMOLED surfaces passed.');
    console.log('Browser: full list replaces the preview, 40 and 80 cards do not overlap, scrolling works, closing restores position, and map and carrier SVG geometry is identical.');
    console.log('Browser: fresh install defaults to AMOLED; saved themes survive; carrier selection uses three SVG buses with functional selection and no overflow.');
    console.log('Browser: real maintenance controls add a draft, test its URL, retain the saved ID, activate, roll back, disable, re-enable and display history. Firebase calls use a fixture adapter; backend behaviour is tested separately.');
    console.log('Browser: favourites animate their position, departure spacing is compact, the new pin follows accent, settings track upward and downward dragging before release, backdrop dismisses, and bus panels default to collapsed.');
  }catch(error){await page.screenshot({path:'test/ui-previews/failure.png'}).catch(()=>{});console.error(await page.evaluate(()=>document.body.innerText).catch(()=>''));console.error(await page.evaluate(()=>[...document.querySelectorAll('.transit-view,.transit-stop-card,.transit-stop-card button')].map(el=>({tag:el.tagName,rect:el.getBoundingClientRect().toJSON(),display:getComputedStyle(el).display}))).catch(()=>[]));console.error('Page errors:',errors);throw error;}
  finally{await browser.close();await new Promise(resolve=>server.close(resolve));fixture.cleanup();}
})().catch(error=>{console.error(error);server.close();fixture.cleanup();process.exitCode=1;});
