import { Device, Operator, Log, Ban } from './types';

export const mockDevices: Device[] = [
  {
    id: '1',
    name: 'iPhone 13 - Marian',
    os: 'iOS 17.5',
    deviceId: 'a1b2c3d4e5f6',
    firstLogin: '12.04.2024, 10:32',
    role: 'Właściciel',
    status: 'Aktywny',
    iconType: 'mobile',
  },
  {
    id: '2',
    name: 'Chrome - Windows 11',
    os: 'Chrome 124',
    deviceId: 'b2c3d4e5f6a7',
    firstLogin: '11.04.2024, 22:15',
    role: 'Administrator',
    status: 'Aktywny',
    iconType: 'desktop',
  },
  {
    id: '3',
    name: 'Samsung S23 - Kasia',
    os: 'Android 14',
    deviceId: 'c3d4e5f6a7b8',
    firstLogin: '11.04.2024, 18:42',
    role: 'Użytkownik',
    status: 'Aktywny',
    iconType: 'mobile',
  },
  {
    id: '4',
    name: 'iPad Pro - Biuro',
    os: 'iPadOS 17.4',
    deviceId: 'd4e5f6a7b8c9',
    firstLogin: '10.04.2024, 09:11',
    role: 'Administrator',
    status: 'Aktywny',
    iconType: 'tablet',
  },
  {
    id: '5',
    name: 'Edge - Windows 10',
    os: 'Edge 123',
    deviceId: 'e5f6a7b8c9d0',
    firstLogin: '09.04.2024, 16:33',
    role: 'Użytkownik',
    status: 'Zablokowany',
    iconType: 'desktop',
  },
  {
    id: '6',
    name: 'Pixel 7 - Tomek',
    os: 'Android 14',
    deviceId: 'f6a7b8c9d0e1',
    firstLogin: '09.04.2024, 13:21',
    role: 'Użytkownik',
    status: 'Aktywny',
    iconType: 'mobile',
  },
];

export const mockOperators: Operator[] = [
  {
    id: '1',
    name: 'Główny Operator',
    role: 'WŁAŚCICIEL',
    innerId: 'op_001',
    lastActive: 'teraz',
    permissions: {
      monitor: true,
      shield: true,
      users: true,
      group: true,
      logs: true,
      ban: true,
canChangeRoles: true,
disableMap: false,
disableStops: false,
      globalSettings: true,
      globalSettingsEdit: true,
    },
  },
  {
    id: '2',
    name: 'Moderator 01',
    role: 'ADMIN',
    innerId: 'op_002',
    lastActive: '2 min temu',
    permissions: {
      monitor: true,
      shield: true,
      users: true,
      group: true,
      logs: true,
      ban: true,
canChangeRoles: true,
disableMap: false,
disableStops: false,
      globalSettings: false,
      globalSettingsEdit: false,
    },
  },
  {
    id: '3',
    name: 'Moderator 02',
    role: 'ADMIN',
    innerId: 'op_003',
    lastActive: '15 min temu',
    permissions: {
      monitor: true,
      shield: true,
      users: true,
      group: true,
      logs: true,
      ban: true,
canChangeRoles: true,
disableMap: false,
disableStops: false,
      globalSettings: true,
      globalSettingsEdit: false,
    },
  },
  {
    id: '4',
    name: 'Operator Podglądu',
    role: 'UŻYTKOWNIK',
    innerId: 'op_004',
    lastActive: '1 godz. temu',
    permissions: {
      monitor: false,
      shield: false,
      users: false,
      group: false,
      logs: false,
      ban: false,
canChangeRoles: false,
disableMap: false,
disableStops: false,
      globalSettings: false,
      globalSettingsEdit: false,
    },
  }
];

export const mockLogs: Log[] = [
  { id: 'l1', date: '20.05.2024', time: '15:07:12', timeAgo: 'teraz', title: 'Urządzenie połączone', description: 'iPhone 13 - Marian (a1b2c3d4e5f6)', location: 'Rzędzów, Polska', category: 'SYSTEM', iconType: 'connect' },
  { id: 'l2', date: '20.05.2024', time: '15:06:58', timeAgo: '1 min temu', title: 'Operator zalogował się', description: 'Moderator 01\nIP: 94.23.124.55', category: 'OPERATOR', iconType: 'login' },
  { id: 'l3', date: '20.05.2024', time: '15:05:41', timeAgo: '2 min temu', title: 'Utracono sygnał GPS', description: 'Samsung S23 - Kasia (c3d4e5f6a7b8)', location: 'Nowa Wieś, Polska', category: 'SYSTEM', iconType: 'gps_lost' },
  { id: 'l4', date: '20.05.2024', time: '15:04:33', timeAgo: '3 min temu', title: 'Nadano bana urządzeniu', description: 'Redmi Note 11 - Tomek (f6a7b8c9d0e1)\nPowód: Za dużo lagów na czacie 😂\nWygasa: 25.05.2024, 23:59', category: 'OPERATOR', iconType: 'ban' },
  { id: 'l5', date: '20.05.2024', time: '15:03:22', timeAgo: '4 min temu', title: 'Zmieniono rolę operatora', description: 'Sebastian Nowak → Administrator\nZmienione przez: Główny Operator', category: 'OPERATOR', iconType: 'role_change' },
  { id: 'l6', date: '20.05.2024', time: '15:02:11', timeAgo: '5 min temu', title: 'Urządzenie rozłączone', description: 'Edge - Windows 10 (e5f6a7b8c9d0)', location: 'Załęże, Polska', category: 'SYSTEM', iconType: 'disconnect' },
  { id: 'l7', date: '19.05.2024', time: '21:01:09', timeAgo: 'Wczoraj', title: 'Wykryto spoofing GPS', description: 'Chrome - Windows 11 (b2c3d4e5f6a7)\nPodejrzana lokalizacja', category: 'SYSTEM', iconType: 'gps_spoof' },
  { id: 'l8', date: '19.05.2024', time: '20:00:33', timeAgo: 'Wczoraj', title: 'Edycja uprawnień roli', description: 'Zaktualizowano uprawnienia: Operator\nZmienione przez: Główny Operator', category: 'OPERATOR', iconType: 'edit_role' },
  { id: 'l9', date: '19.05.2024', time: '14:20:00', timeAgo: 'Wczoraj', title: 'Urządzenie połączone', description: 'iPad Pro - Biuro (d4e5f6a7b8c9)', location: 'Warszawa, Polska', category: 'SYSTEM', iconType: 'connect' },
  { id: 'l10', date: '18.05.2024', time: '09:12:44', timeAgo: '2 dni temu', title: 'Rejestracja nowej sesji', description: 'Logowanie z nowego adresu IP: 81.2.3.44', category: 'SYSTEM', iconType: 'login' },
];

export const mockBans: Ban[] = [
  { id: 'b1', deviceName: 'Redmi Note 11 - Tomek', deviceId: 'f6a7b8c9d0e1', location: 'Rzędzów, Polska', status: 'AKTYWNY', expireIn: '5 dni, 08:52:27', reason: 'Za dużo lagów na czacie 😂', bannedBy: 'Główny Operator', date: '20.05.2024, 15:04' },
  { id: 'b2', deviceName: 'Samsung A53 - Kamil', deviceId: 'd4e5f6a7b8c9', location: 'Miłocin, Polska', status: 'AKTYWNY', expireIn: '2 dni, 03:12:11', reason: 'Spamowanie systemu', bannedBy: 'Moderator 01', date: '19.05.2024, 21:33' },
  { id: 'b3', deviceName: 'iPhone 12 - Bartek', deviceId: 'e1f2a3b4c5d6', location: 'Nowa Wieś, Polska', status: 'AKTYWNY', expireIn: '12 dni, 18:43:05', reason: 'Wykryto spoofing GPS', bannedBy: 'Główny Operator', date: '18.05.2024, 19:11' },
  { id: 'b4', deviceName: 'Pixel 6 - Alicja', deviceId: 'a1b2c3d4e5f6', location: 'Warszawa, Polska', status: 'AKTYWNY', expireIn: '00:45:10', reason: 'Naruszenie regulaminu', bannedBy: 'Moderator 02', date: '20.05.2024, 10:15' },
  { id: 'b5', deviceName: 'MacBook M1 - Jacek', deviceId: '1a2b3c4d5e6f', location: 'Kraków, Polska', status: 'ZAKOŃCZONY', expireIn: 'Wygasł', reason: 'Podejrzane oprogramowanie', bannedBy: 'Główny Operator', date: '10.05.2024, 12:00' },
  { id: 'b6', deviceName: 'Poco X3 - Maciek', deviceId: 'c1d2e3f4a5b6', location: 'Gdańsk, Polska', status: 'AKTYWNY', expireIn: '1 rok', reason: 'Próba oszustwa systemowego', bannedBy: 'Główny Operator', date: '15.05.2024, 08:30' }
];
