'use client';
import {useState,type ReactNode} from 'react';
import {Palette,Shapes,Layers,Sun,Type,Navigation,SlidersHorizontal,RotateCcw,Check,ChevronDown,Bus,MapPin,List,RefreshCw} from 'lucide-react';
import {DEFAULT_INTERFACE_APPEARANCE,type InterfaceAppearance} from '@/lib/interface-appearance';
import {softPanelBackground} from '@/lib/panel-glow';

type Props={value:InterfaceAppearance;onChange:(value:InterfaceAppearance)=>void;dark:boolean;theme:string;accent:string;setTheme:(theme:string)=>void;setAccent:(color:string)=>void;glass:boolean;setGlass:(on:boolean)=>void;glow:boolean;setGlow:(on:boolean)=>void;glowStrength:number;setGlowStrength:(n:number)=>void;lightEffects:boolean;setLightEffects:(on:boolean)=>void};
type NumericKey={ [K in keyof InterfaceAppearance]:InterfaceAppearance[K] extends number?K:never }[keyof InterfaceAppearance];
const accents=[['Turkus','#00a3a2'],['Niebieski','#3b82f6'],['Fiolet','#8b5cf6'],['Róż','#f43f5e'],['Bursztyn','#f59e0b'],['Zieleń','#22c55e'],['Grafit','#64748b'],['Błękit','#06b6d4']];

export default function InterfacePersonalization(p:Props){
  const {value:v,dark}=p,[query,setQuery]=useState(''),[preview,setPreview]=useState('map');
  const set=<K extends keyof InterfaceAppearance>(key:K,next:InterfaceAppearance[K])=>p.onChange({...v,[key]:next});
  const selected=(active:boolean)=>`personal-choice ui-accent-focus ${active?'ui-accent-soft':'bg-current/[.035] border-current/10'}`;
  const slider=(key:NumericKey,label:string,min:number,max:number,step:number,unit='')=><label className="personal-slider"><span className="flex items-center justify-between gap-3"><span>{label}</span><output>{v[key]}{unit}</output></span><input aria-label={label} type="range" min={min} max={max} step={step} value={v[key]} onChange={e=>set(key,Number(e.target.value))}/></label>;
  const toggle=(label:string,on:boolean,change:(value:boolean)=>void,description?:string)=><label className="personal-toggle"><span><span className="block font-medium">{label}</span>{description&&<span className="mt-1 block text-[11px] opacity-60">{description}</span>}</span><input aria-label={label} type="checkbox" role="switch" checked={on} onChange={e=>change(e.target.checked)}/></label>;
  const choices=<K extends keyof InterfaceAppearance>(key:K,label:string,options:[InterfaceAppearance[K],string][]) => <fieldset className="personal-field"><legend>{label}</legend><div className="personal-choices">{options.map(([next,name])=><button key={String(next)} type="button" aria-pressed={v[key]===next} onClick={()=>set(key,next)} className={selected(v[key]===next)}>{name}</button>)}</div></fieldset>;
  const group=(id:string,title:string,subtitle:string,icon:ReactNode,children:ReactNode,keywords:string,open=false)=>{
    if(query&&!`${title} ${subtitle} ${keywords}`.toLocaleLowerCase('pl').includes(query.toLocaleLowerCase('pl')))return null;
    return <details key={id} className="personal-group group" open={query?true:open||undefined}><summary><span className="personal-group-icon">{icon}</span><span className="min-w-0 flex-1"><span className="block font-semibold">{title}</span><span className="mt-1 block text-[11px] opacity-60">{subtitle}</span></span><ChevronDown size={17} className="shrink-0 transition-transform group-open:rotate-180"/></summary><div className="personal-group-body">{children}</div></details>;
  };
  const reset=()=>{p.onChange({...DEFAULT_INTERFACE_APPEARANCE});p.setTheme('dark-oled');p.setAccent('#00A3A2');p.setGlass(true);p.setGlow(false);p.setGlowStrength(40);p.setLightEffects(false);};
  const preset=(name:string)=>{
    const base={...DEFAULT_INTERFACE_APPEARANCE};
    if(name==='Spokojny'){p.onChange({...base,panelRadius:28,cardRadius:24,shadowStrength:15,glowStyle:'graphite',glowSpread:90});p.setTheme('light-warm');p.setAccent('#00A3A2');p.setGlass(true);p.setGlow(true);p.setGlowStrength(35);}
    if(name==='Nocny'){p.onChange({...base,glassOpacity:78,borderStrength:8,glowStyle:'mixed',glowColor:'#8b5cf6',shadowStrength:10});p.setTheme('dark-oled');p.setAccent('#8b5cf6');p.setGlass(true);p.setGlow(true);p.setGlowStrength(50);}
    if(name==='Czytelny'){p.onChange({...base,textScale:115,titleWeight:800,iconSize:28,iconStroke:2.5,density:'spacious',borderStrength:20,reducedMotion:true});p.setTheme('light');p.setAccent('#00A3A2');p.setGlass(false);p.setGlow(false);}
    if(name==='Minimalny'){p.onChange({...base,panelRadius:16,cardRadius:12,controlRadius:8,shadowStrength:0,navIndicator:'pill',density:'compact'});p.setTheme('dark');p.setAccent('#64748b');p.setGlass(false);p.setGlow(false);}
  };
  const fg=dark?'#f1f5f9':'#172536',bg=dark?'#101e26':'#f7fafc';
  return <div data-personalization-panel className="personal-editor">
    <div data-options-appearance className="personal-preview-wrap">
      <div className="flex items-center justify-between gap-2 mb-2"><span className="text-[10px] uppercase tracking-widest opacity-60">Podgląd na żywo</span><span className="text-[10px] opacity-50">Przykładowe dane</span></div>
      <div className="personal-preview" data-interface-preview style={{color:fg,background:dark?'#15252b':'#dae9e4'}}>
        <div className="personal-preview-roads" aria-hidden="true"/>
        <div className={`personal-preview-panel ${p.glass?'pks-glass':''}`} style={{borderRadius:v.panelRadius,backgroundColor:p.glass?undefined:bg,backgroundImage:p.glow?softPanelBackground(v.glowColor,Math.min(p.glowStrength,p.lightEffects?25:100)/100,dark,{style:v.glowStyle,spread:v.glowSpread,placement:v.glowPlacement}):undefined,boxShadow:`0 6px 18px #000000${Math.round(v.shadowStrength*.35).toString(16).padStart(2,'0')}`,borderColor:dark?`rgba(255,255,255,${v.borderStrength/100})`:`rgba(15,23,42,${v.borderStrength/100})`,fontFamily:v.fontFamily==='mono'?'monospace':v.fontFamily==='sans'?'Arial, sans-serif':undefined,letterSpacing:v.letterSpacing}}>
          <div className="flex items-center justify-between gap-2 mb-2" style={{fontWeight:v.titleWeight,fontSize:13*v.textScale/100}}><span className="flex min-w-0 items-center gap-2"><Bus size={v.iconSize*.7} strokeWidth={v.iconStroke} style={{color:p.accent}}/><span className="truncate">{preview==='map'?'PKS Live':preview==='stop'?'Podkarpacka / Matuszczaka':'108 · Rzeszów D.A.'}</span></span><RefreshCw size={15} style={{color:p.accent}}/></div>
          {preview==='map'?<div className="personal-preview-search" style={{borderRadius:v.controlRadius,fontSize:11*v.textScale/100}}>Filtruj linie… <span className="ml-auto" style={{color:p.accent}}>108</span></div>:<div className="flex items-center gap-2" style={{paddingBlock:v.density==='compact'?2:v.density==='spacious'?8:5,fontSize:11*v.textScale/100}}><span className="px-2 py-1 font-bold" style={{borderRadius:v.cardRadius/2,background:p.accent+'1a',color:p.accent}}>108</span><span className="min-w-0 flex-1 truncate">{preview==='stop'?'Rzeszów D.A.':'Następny: Boguchwała'}</span><span style={{fontVariantNumeric:v.tabularNumbers?'tabular-nums':'normal'}}>5 min</span></div>}
        </div>
        {preview==='map'&&<span className="personal-preview-bus" style={{background:p.accent}}><Bus size={18}/><span>108</span></span>}
        <div className="personal-preview-nav" style={{background:p.glass?undefined:bg}}>{([['map','Mapa',<MapPin key="m"/>],['stop','Przystanek',<List key="l"/>],['bus','Autobus',<Bus key="b"/>]] as const).map(([id,label,icon])=><button type="button" key={id} aria-label={`Podgląd: ${label}`} aria-pressed={preview===id} onClick={()=>setPreview(id)} style={{color:preview===id?p.accent:fg,opacity:preview===id?1:v.inactiveOpacity/100,background:preview===id&&v.navIndicator==='pill'?p.accent+'18':undefined,borderTop:preview===id&&v.navIndicator==='line'?`2px solid ${p.accent}`:'2px solid transparent',borderRadius:v.navIndicator==='pill'?v.controlRadius:0}}>{icon}{v.navLabels&&<span>{label}</span>}</button>)}</div>
      </div>
    </div>
    <div className="personal-presets"><span className="text-xs font-semibold">Gotowe zestawy</span><div className="grid grid-cols-2 gap-2 mt-2">{['Spokojny','Nocny','Czytelny','Minimalny'].map(name=><button type="button" key={name} onClick={()=>preset(name)} className={selected(false)}>{name}</button>)}</div></div>
    <label className="personal-search"><SlidersHorizontal size={16}/><input aria-label="Szukaj ustawień personalizacji" placeholder="Znajdź ustawienie…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button type="button" onClick={()=>setQuery('')} aria-label="Wyczyść wyszukiwanie personalizacji">×</button>}</label>
    {group('colors','Motyw i kolory','Motywy, paleta i własny akcent',<Palette size={19}/>,<>
      <div className="grid grid-cols-3 gap-2">{[['system','Systemowy'],['light','Jasny'],['light-warm','Piaskowy'],['dark','Ciemny'],['dark-oled','AMOLED'],['dark-aurora','Aurora']].map(([key,name])=><button type="button" key={key} aria-pressed={p.theme===key} className={selected(p.theme===key)} onClick={()=>p.setTheme(key)}>{name}</button>)}</div>
      <fieldset className="personal-field"><legend>Kolor akcentu</legend><div className="grid grid-cols-4 gap-2">{accents.map(([name,color])=><button type="button" key={name} aria-label={`Personalizacja: akcent ${name}`} aria-pressed={p.accent.toLowerCase()===color} onClick={()=>p.setAccent(color)} className={`${selected(p.accent.toLowerCase()===color)} flex flex-col items-center gap-2`}><span className="flex h-6 w-6 items-center justify-center rounded-full" style={{background:color}}>{p.accent.toLowerCase()===color&&<Check size={14} className="text-white"/>}</span><span className="text-[10px]">{name}</span></button>)}</div></fieldset>
      <label className="personal-color"><span>Własny kolor akcentu</span><span className="ml-auto font-mono text-[10px] opacity-60">{p.accent.toUpperCase()}</span><input aria-label="Własny akcent interfejsu" type="color" value={p.accent} onChange={e=>p.setAccent(e.target.value)}/></label>
      {choices('surfaceTint','Zabarwienie paneli',[['original','Według motywu'],['accent','Akcent'],['warm','Ciepłe']])}
    </>,'akcent własny kolor jasny ciemny amoled aurora',true)}
    {group('shapes','Kształty i głębia','Rogi, obramowania i cienie',<Shapes size={19}/>,<>{slider('panelRadius','Zaokrąglenie paneli',0,36,2,' px')}{slider('cardRadius','Zaokrąglenie kart',0,30,2,' px')}{slider('controlRadius','Zaokrąglenie przycisków',0,24,2,' px')}{slider('borderStrength','Widoczność obramowań',0,40,2,'%')}{slider('shadowStrength','Siła cieni',0,100,5,'%')}</>,'zaokrąglenie paneli kart przycisków widoczność obramowań siła cieni')}
    {group('glass','Szkło i przezroczystość','Krycie, rozmycie i nasycenie',<Layers size={19}/>,<>{toggle('Efekt szkła',p.glass,p.setGlass,'Przezroczyste panele z rozmytym tłem')}{slider('glassOpacity','Krycie tła paneli',20,100,5,'%')}{slider('glassBlur','Rozmycie szkła',0,28,2,' px')}{slider('glassSaturation','Nasycenie szkła',80,180,5,'%')}<p className="personal-note">Krycie i rozmycie działają po włączeniu szkła. Tekst i godziny pozostają wyraźne.</p></>,'efekt szkła krycie tła rozmycie nasycenie przezroczystość')}
    {group('glow','Miękka poświata','Rozmyte plamy bez świecącej obwódki',<Sun size={19}/>,<>
      {toggle('Miękka poświata paneli',p.glow,p.setGlow)}
      <label className="personal-slider"><span className="flex items-center justify-between"><span>Siła poświaty</span><output>{p.glowStrength}%</output></span><input aria-label="Siła miękkiej poświaty" type="range" min="0" max="100" step="5" value={p.glowStrength} onChange={e=>p.setGlowStrength(Number(e.target.value))}/></label>
      {choices('glowStyle','Kolory plam',[['graphite','Grafit'],['accent','Kolorowe'],['mixed','Grafit + kolor']])}
      <label className="personal-color"><span>Kolor poświaty</span><input aria-label="Kolor miękkiej poświaty" type="color" value={v.glowColor} onChange={e=>set('glowColor',e.target.value)}/></label>
      {slider('glowSpread','Rozproszenie plam',40,100,5,'%')}{choices('glowPlacement','Rozmieszczenie',[['corners','W rogach'],['center','Centralnie'],['diagonal','Po przekątnej']])}
    </>,'miękka poświata siła kolor grafit plamy rozproszenie rozmieszczenie')}
    {group('text','Tekst i czytelność','Rozmiar, krój i wyróżnienie tytułów',<Type size={19}/>,<>{slider('textScale','Wielkość tekstu interfejsu',90,120,5,'%')}{choices('fontFamily','Krój pisma',[['system','Systemowy'],['sans','Klasyczny'],['mono','Monospace']])}{slider('titleWeight','Grubość nagłówków',500,800,100)}{slider('letterSpacing','Odstępy między literami',0,.8,.1,' px')}{toggle('Równa szerokość cyfr',v.tabularNumbers,on=>set('tabularNumbers',on),'Godziny i liczby łatwiej porównać')}</>,'wielkość tekstu interfejsu krój pisma grubość nagłówków litery cyfry')}
    {group('nav','Nawigacja i ikony','Etykiety, ikony i aktywna zakładka',<Navigation size={19}/>,<>{slider('iconSize','Rozmiar ikon nawigacji',18,30,2,' px')}{slider('iconStroke','Grubość ikon',1,3,.25)}{toggle('Podpisy pod ikonami',v.navLabels,on=>set('navLabels',on))}{choices('navIndicator','Aktywna zakładka',[['line','Linia'],['pill','Miękkie tło'],['none','Sam kolor']])}{slider('inactiveOpacity','Widoczność nieaktywnych zakładek',45,100,5,'%')}</>,'rozmiar ikon nawigacji grubość podpisy aktywna zakładka widoczność')}
    {group('comfort','Układ i komfort','Odstępy, ruch i lżejsze efekty',<SlidersHorizontal size={19}/>,<>{choices('density','Odstępy w kartach',[['compact','Mniejsze'],['comfortable','Standardowe'],['spacious','Większe']])}{toggle('Ogranicz animacje',v.reducedMotion,on=>set('reducedMotion',on),'Spokojniejsze przejścia i otwieranie paneli')}{toggle('Wyróżnienie wskazanej karty',v.hoverHighlight,on=>set('hoverHighlight',on))}{toggle('Lżejsze efekty',p.lightEffects,p.setLightEffects,'Mniejsze rozmycie i cienie')}</>,'odstępy karty animacje ruch wyróżnienie lżejsze efekty')}
    <button type="button" onClick={reset} className="personal-reset ui-accent-focus"><RotateCcw size={16}/>Przywróć domyślny wygląd</button>
    <p className="personal-note text-center">Ustawienia zapisują się automatycznie na tym urządzeniu.</p>
  </div>;
}
