'use client';
import {useEffect,useState} from 'react';
import {ArrowUp,ArrowDown,Save,Trash2} from 'lucide-react';
import {type InterfaceAppearance,type NavItem} from '@/lib/interface-appearance';
import {PROFILES_KEY,SCHEDULE_KEY,DEFAULT_SCHEDULE,readProfiles,readSchedule,normalizeSchedule,activateProfile,type VisualProfile,type VisualSchedule} from '@/lib/personalization-profiles';

type Props={canOpenAdminEmbed?:boolean;value:InterfaceAppearance;onChange:(value:InterfaceAppearance)=>void;theme:string;accent:string;glass:boolean;glow:boolean;glowStrength:number};
const labels:Record<NavItem,string>={map:'Mapa',stops:'Przystanki',admin:'Admin',options:'Opcje'};
export default function PersonalizationTools(p:Props){
 const [profiles,setProfiles]=useState<VisualProfile[]>([]),[schedule,setSchedule]=useState<VisualSchedule>({...DEFAULT_SCHEDULE}),[name,setName]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{const read=()=>{setProfiles(readProfiles());setSchedule(readSchedule());};read();window.addEventListener('storage',read);window.addEventListener('pks-profiles-changed',read);return()=>{window.removeEventListener('storage',read);window.removeEventListener('pks-profiles-changed',read);};},[]);
 const set=<K extends keyof InterfaceAppearance>(key:K,value:InterfaceAppearance[K])=>p.onChange({...p.value,[key]:value});
 const choice=<K extends keyof InterfaceAppearance>(key:K,title:string,options:[InterfaceAppearance[K],string][])=><fieldset className="personal-field"><legend>{title}</legend><div className="personal-choices">{options.map(([value,label])=><button type="button" key={String(value)} aria-pressed={p.value[key]===value} onClick={()=>set(key,value)} className={`personal-choice ui-accent-focus ${p.value[key]===value?'ui-accent-soft':''}`}>{label}</button>)}</div></fieldset>;
 const saveSchedule=(input:VisualSchedule)=>{const next=normalizeSchedule(input);if(next.dayAt===next.nightAt)next.enabled=false;try{localStorage.removeItem('mks_visual_schedule_applied');localStorage.setItem(SCHEDULE_KEY,JSON.stringify(next));setSchedule(next);window.dispatchEvent(new Event('pks-interface-appearance'));}catch{setMessage('Nie udało się zapisać harmonogramu.');}};
 const store=(next:VisualProfile[])=>{localStorage.setItem(PROFILES_KEY,JSON.stringify(next));setProfiles(next);};
 const capture=(id:string,title:string):VisualProfile=>({id,name:title,updatedAt:Date.now(),appearance:{...p.value,navOrder:[...p.value.navOrder]},theme:p.theme,accent:p.accent,glass:p.glass,glow:p.glow,glowStrength:p.glowStrength});
 const save=()=>{if(!name.trim())return;try{if(profiles.length>=8){setMessage('Możesz zapisać do 8 zestawów. Usuń jeden, aby dodać kolejny.');return;}const next=capture(crypto.randomUUID(),name.trim());store([...profiles,next]);setName('');setMessage(`Zapisano zestaw „${next.name}”.`);if(!schedule.dayProfile)saveSchedule({...schedule,dayProfile:next.id});else if(!schedule.nightProfile)saveSchedule({...schedule,nightProfile:next.id});}catch{setMessage('Nie udało się zapisać zestawu.');}};
 const visibleOrder=p.value.navOrder.filter(id=>id!=='admin'||p.canOpenAdminEmbed);
 const move=(index:number,direction:number)=>{const target=visibleOrder[index+direction];if(!target)return;const order=[...p.value.navOrder],from=order.indexOf(visibleOrder[index]),to=order.indexOf(target);[order[from],order[to]]=[order[to],order[from]];set('navOrder',order);};
 const valid=profiles.some(p=>p.id===schedule.dayProfile)&&profiles.some(p=>p.id===schedule.nightProfile)&&schedule.dayAt!==schedule.nightAt;
 return <div className="personal-tools">
  {choice('startScreen','Ekran startowy',[['map','Mapa'],['stops','Przystanki'],['favorites','Ulubione']])}
  <p className="personal-note">Ekran startowy zmieni się przy kolejnym uruchomieniu. Otwarcie z widżetu prowadzi do jego przystanku.</p>
  <fieldset className="personal-field"><legend>Kolejność zakładek</legend><div className="personal-order">{visibleOrder.map((id,index)=><div key={id}><span>{labels[id]}</span><button type="button" disabled={index===0} onClick={()=>move(index,-1)} aria-label={`Przesuń ${labels[id]} wcześniej`} className="ui-accent-focus"><ArrowUp size={16}/></button><button type="button" disabled={index===visibleOrder.length-1} onClick={()=>move(index,1)} aria-label={`Przesuń ${labels[id]} później`} className="ui-accent-focus"><ArrowDown size={16}/></button></div>)}</div></fieldset>
  {choice('departureView','Widok odjazdów',[['detailed','Szczegółowy'],['simple','Prosty']])}
  <p className="personal-note">Prosty widok ma mniejsze odstępy i ukrywa opis pojazdu. Linia, kierunek, czas, opóźnienia i komunikaty pozostają widoczne.</p>
  {choice('handedness','Obsługa jedną ręką',[['off','Standardowa'],['left','Lewa ręka'],['right','Prawa ręka']])}
  <p className="personal-note">Na telefonie filtr mapy jest bliżej dolnego menu, a przyciski przewoźników i powiększenia są po wybranej stronie.</p>
  <label className="personal-slider"><span>Rozmiar znaczników pojazdów <output>{p.value.markerSize}%</output></span><input aria-label="Rozmiar znaczników pojazdów" type="range" min="80" max="140" step="5" value={p.value.markerSize} onChange={e=>set('markerSize',Number(e.target.value))}/></label>
  {choice('markerLabel','Podpis znacznika',[['line','Numer linii'],['carrier','Przewoźnik'],['icon','Sama ikona']])}
  <fieldset className="personal-field"><legend>Moje zestawy wyglądu</legend><div className="personal-profile-save"><input aria-label="Nazwa własnego zestawu" maxLength={40} placeholder="Np. Mój wieczorny wygląd" value={name} onChange={e=>setName(e.target.value)}/><button type="button" disabled={!name.trim()||profiles.length>=8} onClick={save} className="personal-choice ui-accent-soft ui-accent-focus"><Save size={15}/>Zapisz</button></div><p className="personal-note">Zapisz obecny wygląd wraz z nawigacją i znacznikami. Maksymalnie 8 zestawów.</p>
   <div className="personal-profile-list">{profiles.map(profile=><div key={profile.id}><button type="button" className="ui-accent-text ui-accent-focus" onClick={()=>{try{activateProfile(profile);setMessage(`Zastosowano zestaw „${profile.name}”.`);}catch{setMessage('Nie udało się zastosować zestawu.');}}} aria-label={`Zastosuj zestaw ${profile.name}`}>{profile.name}</button><button type="button" className="ui-accent-focus" aria-label={`Nadpisz zestaw ${profile.name} obecnym wyglądem`} onClick={()=>{try{store(profiles.map(item=>item.id===profile.id?capture(profile.id,profile.name):item));window.dispatchEvent(new Event('pks-interface-appearance'));setMessage(`Zaktualizowano zestaw „${profile.name}”.`);}catch{setMessage('Nie udało się zapisać zestawu.');}}}><Save size={15}/></button><button type="button" className="ui-accent-focus" aria-label={`Usuń zestaw ${profile.name}`} onClick={()=>{try{store(profiles.filter(item=>item.id!==profile.id));if([schedule.dayProfile,schedule.nightProfile].includes(profile.id))saveSchedule({...schedule,enabled:false,dayProfile:schedule.dayProfile===profile.id?'':schedule.dayProfile,nightProfile:schedule.nightProfile===profile.id?'':schedule.nightProfile});setMessage(`Usunięto zestaw „${profile.name}”.`);}catch{setMessage('Nie udało się usunąć zestawu.');}}}><Trash2 size={15}/></button></div>)}</div>
  </fieldset>
  <fieldset className="personal-field"><legend>Automatyczny wygląd dnia i nocy</legend><div className="personal-schedule">{(['day','night'] as const).map(slot=><div key={slot}><label>{slot==='day'?'Dzień od':'Noc od'}<input aria-label={slot==='day'?'Początek dnia':'Początek nocy'} type="time" value={slot==='day'?schedule.dayAt:schedule.nightAt} onChange={e=>saveSchedule({...schedule,[slot==='day'?'dayAt':'nightAt']:e.target.value})}/></label><label>Zestaw {slot==='day'?'dzienny':'nocny'}<select aria-label={slot==='day'?'Zestaw dzienny':'Zestaw nocny'} value={slot==='day'?schedule.dayProfile:schedule.nightProfile} onChange={e=>saveSchedule({...schedule,[slot==='day'?'dayProfile':'nightProfile']:e.target.value})}><option value="">Wybierz zestaw</option>{profiles.map(profile=><option value={profile.id} key={profile.id}>{profile.name}</option>)}</select></label></div>)}</div>
  <label className="personal-toggle"><span>Automatycznie zmieniaj wygląd</span><input aria-label="Automatycznie zmieniaj wygląd" role="switch" type="checkbox" checked={schedule.enabled} disabled={!valid} onChange={e=>saveSchedule({...schedule,enabled:e.target.checked})}/></label>
  <p className="personal-note">{valid?'Godziny według zegara telefonu. Wygląd zmienia się również po powrocie do aplikacji.':'Wybierz zapisane zestawy i dwie różne godziny, aby włączyć harmonogram.'}</p>
  </fieldset>
  {message&&<p role="status" className="personal-note">{message}</p>}
 </div>;
}
